name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Code checkout করো
      uses: actions/checkout@v3

    - name: Docker build করো
      run: docker build -t flask-app .

    - name: Test করো
      run: docker run flask-app python -c "import flask; print('Flask OK!')"

    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VMHOST }}
        username: ${{ secrets.VMUSER }}
        password: ${{ secrets.VMPASSWORD }}
        script: |
          cd ~/myapp
          git pull origin main
          docker build -t flask-app .
          docker stop saikat-app || true
          docker rm saikat-app || true
          docker run -d --name saikat-app -p 5000:5000 flask-app
